const foundationJobDefinitions = [
  {
    key: 'foundation-verify',
    title: 'Foundation Verifier',
    jobType: 'health_check',
    lane: 'health',
    priority: 'P0',
    cadence: 'after code or source-contract changes',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 60,
    maxRuntimeSeconds: 180,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'foundation:verify'],
    sourceIds: [],
    description: 'Runs the core Foundation smoke checks so the system knows whether repo/API/source truth still lines up.',
    nextAction: 'Run after meaningful builds and before checkpoints.',
  },
  {
    key: 'shared-comms-coverage',
    title: 'Shared Comms Coverage',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P0',
    cadence: 'daily and after archive backfills',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 240,
    maxRuntimeSeconds: 180,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'shared-comms:coverage'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Reports artifact/candidate coverage by source so extraction depth is visible instead of guessed.',
    nextAction: 'Run before deciding whether to backfill more or build synthesis.',
  },
  {
    key: 'llm-auth-audit',
    title: 'LLM Auth Path Audit',
    jobType: 'llm_audit',
    lane: 'model',
    priority: 'P0',
    cadence: 'before router migration and after credential changes',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 180,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'llm:auth-audit'],
    sourceIds: [],
    description: 'Seeds router config and probes model/auth paths without migrating real workloads.',
    nextAction: 'Run manually before any extraction/synthesis script is moved behind the router.',
  },
  {
    key: 'extraction-control-seed',
    title: 'Extraction Control Seed',
    jobType: 'control_plane',
    lane: 'extract',
    priority: 'P0',
    cadence: 'after source/backfill strategy changes',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 120,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'extraction:control-seed'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001', 'SRC-GDRIVE-001', 'SRC-SKOOL-001', 'SRC-VIDEO-001', 'SRC-LOOM-001'],
    description: 'Seeds the current-day and bounded-backfill crawl target ledger so extraction work is visible before it is automated.',
    nextAction: 'Use this as the control-plane map before scheduling current-day sync or historical backfill workers.',
  },
  {
    key: 'gmail-sync-current',
    title: 'Gmail Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'every 2 hours',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 120,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=gmail-current-day'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Runs recent delegated team Gmail sync through the extraction target ledger so today stays current without a manual builder-chat pull.',
    nextAction: 'Watch first scheduled runs; keep historical Gmail backfill manual until current-day stays clean.',
  },
  {
    key: 'missive-sync-current',
    title: 'Missive Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'every 2 hours',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 120,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=missive-current-day'],
    sourceIds: ['SRC-MISSIVE-001'],
    description: 'Runs recent Missive sync through the extraction target ledger so email-side team context, including internal comments, stays current.',
    nextAction: 'Watch first scheduled runs; keep Gmail/manual backfill off until this lane stays clean.',
  },
  {
    key: 'meeting-notes-sync-current',
    title: 'Meeting Notes Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'daily',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=meetings-current-day'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Runs recent Google meeting notes/transcripts through the extraction target ledger so current meeting context stays fresh.',
    nextAction: 'Keep manual until partial-run alerting and failed-item retry proof are stable.',
  },
  {
    key: 'meeting-notes-retry-failed',
    title: 'Meeting Notes Failed-Item Retry',
    jobType: 'recovery',
    lane: 'archive',
    priority: 'P1',
    cadence: 'after meeting crawl partial/failure',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'meeting-notes:retry-failed'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Retries only failed meeting crawl items from the source_crawl_items ledger instead of rerunning the whole current-day window.',
    nextAction: 'Run manually after a partial meeting sync; schedule only after retry semantics are proven.',
  },
  {
    key: 'drive-corpus-inventory-bite',
    title: 'Drive Corpus Inventory Bite',
    jobType: 'corpus_inventory',
    lane: 'archive',
    priority: 'P1',
    cadence: 'manual one-folder bite',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=drive-corpus-backfill'],
    sourceIds: ['SRC-GDRIVE-001'],
    description: 'Inventories one Google Drive corpus folder/page into the crawl ledger without moving, copying, exporting, or using an LLM.',
    nextAction: 'Run manually for the first safe Drive bite; schedule only after folder cursor and review semantics are proven.',
  },
  {
    key: 'video-link-inventory-bite',
    title: 'Video Link Inventory Bite',
    jobType: 'corpus_inventory',
    lane: 'archive',
    priority: 'P1',
    cadence: 'manual inventory bite',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=video-link-inventory'],
    sourceIds: ['SRC-VIDEO-001', 'SRC-LOOM-001', 'SRC-GDRIVE-001', 'SRC-SKOOL-001', 'SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Inventories Loom, Drive, YouTube, Vimeo, Wistia, Zoom, and Skool media links from existing archives/crawl ledgers without logging into platforms or extracting content.',
    nextAction: 'Run manually to build the URL manifest; validate Apify/Loom/Skool extractors on a small authorized batch later.',
  },
  {
    key: 'gmail-extract-latest',
    title: 'Gmail Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'after Gmail sync',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'gmail:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=1'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Extracts governed candidates from archived Gmail threads without a successful processing run for the current content hash.',
    nextAction: 'Run manually as a paced subscription miner; raise limits only after route latency and spacing are stable.',
  },
  {
    key: 'missive-extract-latest',
    title: 'Missive Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'after Missive sync',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'missive:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=1'],
    sourceIds: ['SRC-MISSIVE-001'],
    description: 'Extracts governed candidates from archived Missive conversations without a successful processing run for the current content hash, including internal comments.',
    nextAction: 'Run manually as a paced subscription miner; raise limits only after route latency and spacing are stable.',
  },
  {
    key: 'meeting-transcript-gaps',
    title: 'Meeting Transcript Gap Report',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P1',
    cadence: 'weekly',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 300,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'meeting-notes:report-gaps'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Finds recurring meetings and organizers with missing transcripts so Meet defaults can be fixed.',
    nextAction: 'Run after the next few meetings to confirm the Gemini default change worked.',
  },
  {
    key: 'meeting-transcript-recent-gap-verify',
    title: 'Meeting Recent Gap Verifier',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P1',
    cadence: 'after recent gap report shows missing transcript artifacts',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'meeting-notes:verify-recent-gaps', '--', '--days=14'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Classifies recent missing transcript artifacts as true missing, parser/tab miss, owner/account path issue, or meeting-key mismatch before meeting sync is scheduled.',
    nextAction: 'Run manually; use the repair command only for parser/account misses after the report is reviewed.',
  },
  {
    key: 'meeting-transcripts-extract-backlog',
    title: 'Meeting Transcript Extraction Backlog',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'manual daily bite until backlog clears',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'meeting-notes:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=1'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Mines archived meeting transcripts without a successful processing run for the current content hash using the subscription route with long per-call windows.',
    nextAction: 'Run manually one transcript at a time; this is a deep miner that feeds Strategy Hub and action routing, not a digest job.',
  },
  {
    key: 'admin-deal-review-readonly',
    title: 'Admin Deal Review Read-Only',
    jobType: 'review',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'every 6 hours when queued rows exist',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 360,
    maxRuntimeSeconds: 600,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'deal-review:admin', '--', '--queued', '--limit=10'],
    sourceIds: ['SRC-OWNERS-001', 'SRC-FUB-001'],
    servesHubs: ['ops'],
    systemSummary: 'Inspects queued closed/firm Owners deal rows against FUB joins and current deal-quality rules without writing back to the sheet.',
    systemInputs: ['SRC-OWNERS-001 Admin deal rows', 'SRC-FUB-001 person records', 'Queued review action cells'],
    systemOutputs: ['Ops deal-review queue signals', 'Read-only issue findings', 'Foundation job run status'],
    description: 'Reads queued closed deals and FUB joins without writing sheet findings.',
    nextAction: 'Foundation inspection is running. Keep write mode and Ops Hub assignment separate and approval-gated.',
  },
  {
    key: 'conditional-deal-review-readonly',
    title: 'Conditional Deal Review Read-Only',
    jobType: 'review',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'every 6 hours when queued rows exist',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 360,
    maxRuntimeSeconds: 600,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'deal-review:conditional', '--', '--queued', '--limit=10'],
    sourceIds: ['SRC-OWNERS-001', 'SRC-FUB-001'],
    servesHubs: ['ops'],
    systemSummary: 'Inspects queued conditional/listing rows against FUB identity, stage, agent, and address parity without writing back to the sheet.',
    systemInputs: ['Listings and Conditional Deals rows', 'SRC-FUB-001 person records', 'Queued conditional review action cells'],
    systemOutputs: ['Ops conditional-review queue signals', 'Read-only issue findings', 'Foundation job run status'],
    description: 'Reads queued conditional/listing rows and FUB joins without writing sheet findings.',
    nextAction: 'Foundation inspection is running. Keep write mode and Ops Hub assignment separate and approval-gated.',
  },
  {
    key: 'shared-comms-intelligence-bite',
    title: 'Strategy Intelligence Synthesis Bite',
    jobType: 'intelligence_bite',
    lane: 'synthesis',
    priority: 'P0',
    cadence: 'manual during strategy prep or action review',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'shared-comms:intelligence-bite'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Synthesizes already-mined shared-comms candidates into Strategy Hub/action-router input. Extraction miners run separately so slow subscription calls do not block leadership work.',
    nextAction: 'Run monitored synthesis-only proofs, then route synthesized items into decisions, contradictions, and owner-bound actions.',
  },
  {
    key: 'shared-comms-synthesis-v1',
    title: 'Shared Comms Strategy Synthesis V1',
    jobType: 'synthesis',
    lane: 'synthesis',
    priority: 'P0',
    cadence: 'after fresh extraction batches',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'synthesis:brief', '--', '--limit=120', '--maxItems=12'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Turns candidates and source-backed facts into ranked Strategy Hub/action-router input instead of a raw mining dump.',
    nextAction: 'Run monitored subscription-route proofs with the long synthesis timeout, then connect outputs to the action router.',
  },
]

export function getFoundationJobDefinitions() {
  return foundationJobDefinitions.map(job => ({
    ...job,
    args: job.args.slice(),
    sourceIds: job.sourceIds.slice(),
  }))
}

export function getFoundationJobDefinition(jobKey) {
  const normalized = String(jobKey || '').trim()
  return getFoundationJobDefinitions().find(job => job.key === normalized) || null
}

export function getFoundationJobRuntime(job, latestRun, now = new Date()) {
  const runtimeMode = job.runtimeMode || (job.enabled ? 'manual' : 'paused')
  const scheduleEveryMinutes = Number(job.scheduleEveryMinutes) > 0 ? Number(job.scheduleEveryMinutes) : null
  const latestTime = latestRun?.finishedAt || latestRun?.startedAt || latestRun?.createdAt || null
  const latestAt = latestTime ? new Date(latestTime) : null
  const latestValid = latestAt && !Number.isNaN(latestAt.getTime())
  const running = latestRun?.status === 'running' || latestRun?.status === 'queued'

  if (!job.enabled || runtimeMode === 'paused') {
    return {
      runtimeMode: 'paused',
      due: false,
      nextRunAt: null,
      scheduleStatus: 'paused',
      scheduleDetail: job.pauseReason ? `Paused: ${job.pauseReason}` : 'Paused or disabled.',
    }
  }

  if (runtimeMode !== 'scheduled') {
    return {
      runtimeMode: 'manual',
      due: false,
      nextRunAt: null,
      scheduleStatus: 'manual',
      scheduleDetail: 'Manual-only until explicitly scheduled.',
    }
  }

  if (!scheduleEveryMinutes) {
    return {
      runtimeMode: 'manual',
      due: false,
      nextRunAt: null,
      scheduleStatus: 'manual',
      scheduleDetail: 'No schedule interval configured.',
    }
  }

  if (!latestValid) {
    return {
      runtimeMode: 'scheduled',
      due: !running,
      nextRunAt: now.toISOString(),
      scheduleStatus: running ? 'running' : 'due',
      scheduleDetail: running ? 'Running now.' : 'Due now: no prior run recorded.',
    }
  }

  const nextRun = new Date(latestAt.getTime() + scheduleEveryMinutes * 60 * 1000)
  const due = !running && nextRun.getTime() <= now.getTime()
  const minutesUntilDue = Math.ceil((nextRun.getTime() - now.getTime()) / 60000)

  return {
    runtimeMode: 'scheduled',
    due,
    nextRunAt: nextRun.toISOString(),
    scheduleStatus: running ? 'running' : due ? 'due' : 'scheduled',
    scheduleDetail: running
      ? 'Running now.'
      : due
        ? `Due now. Scheduled every ${scheduleEveryMinutes} minutes.`
        : `Next run in ${Math.max(0, minutesUntilDue)} minutes.`,
  }
}
