const foundationJobDefinitions = [
  {
    key: 'foundation-verify',
    title: 'Foundation Verifier',
    jobType: 'health_check',
    lane: 'health',
    priority: 'P0',
    cadence: 'after code or source-contract changes',
    enabled: true,
    command: 'npm',
    args: ['run', 'foundation:verify'],
    sourceIds: [],
    description: 'Runs the core Foundation smoke checks so the system knows whether repo/API/source truth still lines up.',
    nextAction: 'Run after meaningful builds and before checkpoints.',
  },
  {
    key: 'shared-comms-coverage',
    title: 'Shared Comms Coverage',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P0',
    cadence: 'daily and after archive backfills',
    enabled: true,
    command: 'npm',
    args: ['run', 'shared-comms:coverage'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Reports artifact/candidate coverage by source so extraction depth is visible instead of guessed.',
    nextAction: 'Run before deciding whether to backfill more or build synthesis.',
  },
  {
    key: 'gmail-sync-current',
    title: 'Gmail Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'daily',
    enabled: true,
    command: 'npm',
    args: ['run', 'gmail:sync-archive', '--', '--team=true', '--limit=25', '--query=newer_than:2d'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Archives recent delegated team Gmail threads so today stays current without a manual builder-chat pull.',
    nextAction: 'Move into scheduler after the manual runner proves stable.',
  },
  {
    key: 'missive-sync-current',
    title: 'Missive Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'daily',
    enabled: true,
    command: 'npm',
    args: ['run', 'missive:sync-archive', '--', '--all=true', '--limit=100', '--pageSize=50'],
    sourceIds: ['SRC-MISSIVE-001'],
    description: 'Archives recent Missive conversations and internal comments so email-side team context stays current.',
    nextAction: 'Move into scheduler after cursor/rate-limit behavior is consistently clean.',
  },
  {
    key: 'gmail-extract-latest',
    title: 'Gmail Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'after Gmail sync',
    enabled: true,
    command: 'npm',
    args: ['run', 'gmail:extract-candidates', '--', '--limit=50'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Extracts governed candidates from the latest archived Gmail threads.',
    nextAction: 'Replace offset-based manual chunks with unprocessed-artifact targeting.',
  },
  {
    key: 'missive-extract-latest',
    title: 'Missive Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'after Missive sync',
    enabled: true,
    command: 'npm',
    args: ['run', 'missive:extract-candidates', '--', '--limit=50'],
    sourceIds: ['SRC-MISSIVE-001'],
    description: 'Extracts governed candidates from archived Missive conversations, including internal comments.',
    nextAction: 'Replace offset-based manual chunks with unprocessed-artifact targeting.',
  },
  {
    key: 'meeting-transcript-gaps',
    title: 'Meeting Transcript Gap Report',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P1',
    cadence: 'weekly',
    enabled: true,
    command: 'npm',
    args: ['run', 'meeting-notes:report-gaps'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Finds recurring meetings and organizers with missing transcripts so Meet defaults can be fixed.',
    nextAction: 'Run after the next few meetings to confirm the Gemini default change worked.',
  },
  {
    key: 'admin-deal-review-readonly',
    title: 'Admin Deal Review Read-Only',
    jobType: 'review',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'daily when queued rows exist',
    enabled: true,
    command: 'npm',
    args: ['run', 'deal-review:admin', '--', '--queued', '--limit=10'],
    sourceIds: ['SRC-OWNERS-001', 'SRC-FUB-001'],
    description: 'Reads queued closed deals and FUB joins without writing sheet findings.',
    nextAction: 'Keep write mode separate and approval-gated.',
  },
  {
    key: 'conditional-deal-review-readonly',
    title: 'Conditional Deal Review Read-Only',
    jobType: 'review',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'daily when queued rows exist',
    enabled: true,
    command: 'npm',
    args: ['run', 'deal-review:conditional', '--', '--queued', '--limit=10'],
    sourceIds: ['SRC-OWNERS-001', 'SRC-FUB-001'],
    description: 'Reads queued conditional/listing rows and FUB joins without writing sheet findings.',
    nextAction: 'Keep write mode separate and approval-gated.',
  },
  {
    key: 'shared-comms-synthesis-v1',
    title: 'Shared Comms Synthesis V1',
    jobType: 'synthesis',
    lane: 'synthesis',
    priority: 'P0',
    cadence: 'after fresh extraction batches',
    enabled: true,
    command: 'npm',
    args: ['run', 'synthesis:brief', '--', '--limit=120', '--maxItems=12'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Turns candidates and source-backed facts into a short ranked synthesis output instead of a raw mining dump.',
    nextAction: 'Stabilize JSON/output reliability, then make this the first recurring intelligence brief job.',
  },
]

export function getFoundationJobDefinitions() {
  return foundationJobDefinitions.map(job => ({
    ...job,
    args: job.args.slice(),
    sourceIds: job.sourceIds.slice(),
  }))
}

export function getFoundationJobDefinition(jobKey) {
  const normalized = String(jobKey || '').trim()
  return getFoundationJobDefinitions().find(job => job.key === normalized) || null
}
