// Compatibility facade only. New code should import the owning domain module.
export {
  FOUNDATION_DB_INIT_SEED_SPLIT_CARD_ID,
  FOUNDATION_DB_READ_ONLY_GATE_TABLES,
  assertFoundationDbReadyForReadOnlyGate,
  bootstrapFoundationDb,
  buildFoundationDbInitSeedSplitDogfoodProof,
  closeFoundationDb,
  getFoundationDbConstraintAudit,
  getFoundationDbReadOnlyGateReadiness,
  initFoundationDb,
  resetFoundationDb,
  withFoundationAdvisoryLock,
} from './foundation-db-session.js'

export {
  BACKLOG_STORE_CONCURRENCY_CARD_ID,
  CURRENT_SPRINT_MUTATION_GUARDS_CARD_ID,
  FoundationCurrentSprintMutationGuardError,
  buildCurrentSprintMutationGuardsDogfoodProof,
  createBacklogItem,
  getActiveFoundationCurrentSprint,
  getBacklogItemsByIds,
  getBacklogSeedDriftSnapshot,
  getFoundationBacklogIdPrefixes,
  getFoundationBacklogScopes,
  getPlanCriticRunsByCardIds,
  updateBacklogItem,
  upsertFoundationCurrentSprintOverlay,
} from './foundation-backlog-sprint-db.js'

export {
  classifySourceCrawlItemRetries,
  finishSourceCrawlTargetRun,
  getDriveCorpusInventorySnapshot,
  getExtractionControlSnapshot,
  getExtractionRunHardeningSnapshot,
  getLatestDriveAccessPreflightRun,
  getLatestMeetingVaultAclAudit,
  getLatestMeetingVaultAutoEnforcementRun,
  getMeetingVaultLegacyExceptions,
  getRetryableSourceCrawlItems,
  getSourceContractRegistrySnapshot,
  getSourceCrawlItemsByExternalId,
  getSourceMaturityOperationalMetrics,
  getStaleSourceCrawlTargetRuns,
  leaseRetryableSourceCrawlItems,
  leaseSourceCrawlTarget,
  listDriveContentExtractionQueue,
  listMeetingRawDriveFileCandidates,
  listSourceCrawlItems,
  listVideoContentExtractionQueue,
  markSourceCrawlItemAttemptFinished,
  markSourceCrawlItemAttemptStarted,
  markStaleSourceCrawlItems,
  markStaleSourceCrawlTargetRuns,
  recordDriveAccessPreflightRun,
  recordMeetingVaultAclAudit,
  recordMeetingVaultAutoEnforcementRun,
  syncSourceContractRegistryTable,
  upsertSourceCrawlItem,
  upsertSourceCrawlTarget,
} from './foundation-source-crawl-db.js'

export {
  applySharedCommunicationCandidateToBacklog,
  applySharedCommunicationCandidateToDecision,
  applySharedCommunicationCandidateToQuestion,
  buildSynthesisVerificationDbReport,
  getSharedCommunicationArchiveSnapshot,
  getSharedCommunicationArtifactsForProcessing,
  getSharedCommunicationArtifactsWithoutCandidatesForProcessing,
  getSharedCommunicationCandidateSnapshot,
  getSharedCommunicationCoverageSnapshot,
  getSharedCommunicationExistingArtifactsByExternalId,
  getSharedCommunicationExistingExternalIds,
  getSharedCommunicationProcessingProvenanceGaps,
  getSharedCommunicationSourceStats,
  getSharedCommunicationSynthesisSnapshot,
  recordSharedCommunicationArtifactProcessingRun,
  recordSharedCommunicationSynthesisRun,
  rejectSharedCommunicationCandidatesByExtractionMethod,
  rejectSharedCommunicationCandidatesForArtifacts,
  searchSharedCommunicationArtifactsForContext,
  updateSharedCommunicationCandidateStatus,
  upsertSharedCommunicationArtifact,
  upsertSharedCommunicationCandidate,
} from './foundation-shared-comms-db.js'

export {
  createFoundationJobRun,
  createLlmCall,
  finishFoundationJobRun,
  finishLlmCall,
  getFoundationJobControl,
  getFoundationJobRunById,
  getFoundationJobRunSnapshot,
  getFoundationJobScheduleIndex,
  getFoundationRuntimeStatus,
  getLlmRuntimeSnapshot,
  getStaleLlmCalls,
  listLlmCalls,
  markFoundationJobRunStopped,
  markStaleFoundationJobRuns,
  markStaleLlmCalls,
  recordFoundationRuntimeStatus,
  recordLlmRouteProbe,
  updateFoundationJobControl,
  updateFoundationJobRunMetadata,
  upsertLlmCredential,
  upsertLlmRoute,
} from './foundation-runtime-jobs-db.js'

export {
  captureFoundationFeedbackItem,
  createAgentFeedbackReminderAttempt,
  createAgentFeedbackResponseNotification,
  createAgentFeedbackSendAttempt,
  getActiveAgentFeedbackSendAttempt,
  getAgentFeedbackReminderAttemptBySlot,
  getAgentFeedbackResponseNotificationByResponseId,
  getAgentOnboardingFeedbackResponseByTokenHash,
  getAgentOnboardingFeedbackResponseForMilestone,
  getFubLeadSourceSnapshot,
  listAgentFeedbackReminderAttemptsForMilestone,
  listAgentFeedbackSendAttemptsForMilestone,
  listAgentFeedbackSendAttemptsForRunId,
  listAgentOnboardingFeedbackResponsesForMilestone,
  listFoundationFeedbackItems,
  listFoundationUsers,
  listFubLeadSourceRules,
  listSalesListingAssignments,
  listSalesListingCases,
  recordReviewQueueChange,
  recordSourceDriftChange,
  saveFubLeadSourceSnapshot,
  supersedeAgentFeedbackSendAttemptForRepair,
  supersedeAgentOnboardingFeedbackResponseForRepair,
  updateAgentFeedbackReminderAttemptStatus,
  updateAgentFeedbackResponseNotificationStatus,
  updateAgentFeedbackSendAttemptStatus,
  upsertAgentOnboardingFeedbackResponse,
  upsertFubLeadSourceRule,
  upsertSalesListingAssignment,
} from './foundation-people-sales-db.js'

export {
  approvePendingDocUpdate,
  createDecision,
  createOpenQuestion,
  createPendingDocUpdate,
  getBusinessAtomDashboardSnapshot,
  getCanonicalDecisionCategories,
  getDocSourceSnapshot,
  getFoundationCoreSnapshot,
  getFoundationSnapshot,
  getLatestChangeEventForEntity,
  getPendingDocUpdate,
  getRecentChangeEvents,
  getStrategyGoalTruthSnapshot,
  getStrategyHubSnapshot,
  getStrategyOperatingTruthSnapshot,
  getStrategyPreworkCoverageSnapshot,
  listFoundationAcknowledgedStates,
  listPendingDocUpdates,
  markPendingDocUpdateApplied,
  markPendingDocUpdateFailed,
  recordActionRouteCuration,
  recordFoundationIncrementalVerifierRun,
  rejectPendingDocUpdate,
  saveStrategyHubSnapshot,
  updateDecision,
  updateOpenQuestion,
  upsertFoundationAcknowledgedState,
} from './foundation-strategy-docs-db.js'

export {
  applyApprovedActionRoute,
  approveActionRoute,
  buildRetrievalEmbeddingInput,
  collectSourceBackedSynthesisFacts,
  getActionRoute,
  getActionRouterSnapshot,
  getIntelligenceAtomSpineSnapshot,
  getIntelligenceJobLedgerSnapshot,
  getIntelligenceReportBundle,
  getIntelligenceRetrievalSnapshot,
  getSynthesisEngineSnapshot,
  getSynthesisFactsSnapshot,
  listYoutubeFullWatchReportArtifacts,
  promoteSharedCommunicationCandidatesToAtoms,
  proposeActionRoutes,
  queryIntelligenceAtomsForScoper,
  querySynthesisFacts,
  recordIntelligenceAtomHit,
  recordRetrievalRun,
  rejectActionRoute,
  rerouteActionRoute,
  runGovernedSynthesis,
  searchIntelligenceChunks,
  searchIntelligenceChunksSemantic,
  searchIntelligenceEvidenceHybrid,
  selectRetrievalChunksForEmbedding,
  upsertIntelligenceAtom,
  upsertIntelligenceJobRun,
  upsertIntelligenceReportArtifact,
  upsertRetrievalChunk,
  upsertRetrievalChunkEmbedding,
  upsertSynthesisFactsBundle,
} from './foundation-intelligence-db.js'
