const foundationJobDefinitions = [
  {
    key: 'foundation-verify',
    title: 'Foundation Verifier',
    jobType: 'health_check',
    lane: 'health',
    priority: 'P0',
    cadence: 'after code or source-contract changes',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 60,
    maxRuntimeSeconds: 180,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'foundation:verify'],
    sourceIds: [],
    description: 'Runs the core Foundation smoke checks so the system knows whether repo/API/source truth still lines up.',
    nextAction: 'Run after meaningful builds and before checkpoints.',
  },
  {
    key: 'shared-comms-coverage',
    title: 'Shared Comms Coverage',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P0',
    cadence: 'daily and after archive backfills',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 240,
    maxRuntimeSeconds: 180,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'shared-comms:coverage'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Reports artifact/candidate coverage by source so extraction depth is visible instead of guessed.',
    nextAction: 'Run before deciding whether to backfill more or build synthesis.',
  },
  {
    key: 'llm-auth-audit',
    title: 'LLM Auth Path Audit',
    jobType: 'llm_audit',
    lane: 'model',
    priority: 'P0',
    cadence: 'before router migration and after credential changes',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 180,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'llm:auth-audit'],
    sourceIds: [],
    description: 'Seeds router config and probes model/auth paths without migrating real workloads.',
    nextAction: 'Run manually before any extraction/synthesis script is moved behind the router.',
  },
  {
    key: 'extraction-control-seed',
    title: 'Extraction Control Seed',
    jobType: 'control_plane',
    lane: 'extract',
    priority: 'P0',
    cadence: 'after source/backfill strategy changes',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 120,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'extraction:control-seed'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001', 'SRC-GDRIVE-001', 'SRC-SKOOL-001', 'SRC-VIDEO-001', 'SRC-LOOM-001'],
    description: 'Seeds the current-day and bounded-backfill crawl target ledger so extraction work is visible before it is automated.',
    nextAction: 'Use this as the control-plane map before scheduling current-day sync or historical backfill workers.',
  },
  {
    key: 'gmail-sync-current',
    title: 'Gmail Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'every 2 hours',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 120,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=gmail-current-day'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Runs recent delegated team Gmail sync through the extraction target ledger so today stays current without a manual builder-chat pull.',
    nextAction: 'Watch first scheduled runs; keep historical Gmail backfill manual until current-day stays clean.',
  },
  {
    key: 'missive-sync-current',
    title: 'Missive Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'every 2 hours',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 120,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=missive-current-day'],
    sourceIds: ['SRC-MISSIVE-001'],
    description: 'Runs recent Missive sync through the extraction target ledger so email-side team context, including internal comments, stays current.',
    nextAction: 'Watch first scheduled runs; keep Gmail/manual backfill off until this lane stays clean.',
  },
  {
    key: 'email-attachment-extract-bite',
    title: 'Email Attachment Extraction Bite',
    jobType: 'corpus_extraction',
    lane: 'extract',
    priority: 'P0',
    cadence: 'daily mission: five Gmail PDF/text attachment outputs',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=email-attachments-backfill'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Extracts Gmail PDF/text attachments into source-backed artifacts with explicit skips for unsupported media, Office, OCR, and calendar attachment classes.',
    nextAction: 'Run as a small daily quota mission. Add Missive attachment proof and Office/OCR/media attachment extractors as explicit follow-on lanes.',
  },
  {
    key: 'meeting-notes-sync-current',
    title: 'Meeting Notes Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P0',
    cadence: 'daily',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=meetings-current-day'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Runs recent Google meeting notes/transcripts through the extraction target ledger so current meeting context stays fresh.',
    nextAction: 'Run daily for new meeting notes/transcripts; use the retry job only for item-level partial failures.',
  },
  {
    key: 'meeting-notes-retry-failed',
    title: 'Meeting Notes Failed-Item Retry',
    jobType: 'recovery',
    lane: 'archive',
    priority: 'P1',
    cadence: 'after meeting crawl partial/failure',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'meeting-notes:retry-failed'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Retries only failed meeting crawl items from the source_crawl_items ledger instead of rerunning the whole current-day window.',
    nextAction: 'Run manually after a partial meeting sync; schedule only after retry semantics are proven.',
  },
  {
    key: 'slack-sync-current',
    title: 'Slack Current Sync',
    jobType: 'current_sync',
    lane: 'archive',
    priority: 'P1',
    cadence: 'daily 48-hour window',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 600,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=slack-current-day'],
    sourceIds: ['SRC-SLACK-001'],
    description: 'Runs recent Slack thread sync through the extraction target ledger so strategy prep can refresh Slack signal without a broad historical backfill.',
    nextAction: 'Run daily for current Slack signal; keep historical Slack as a separate extraction mission.',
  },
  {
    key: 'slack-extract-latest',
    title: 'Slack Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'daily history mission after Slack sync',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'slack:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=1'],
    sourceIds: ['SRC-SLACK-001'],
    description: 'Extracts governed candidates from archived Slack threads using the subscription route with a long worker-managed timeout.',
    nextAction: 'Run as a daily quota mission. Start at one Slack thread per day until route latency is measured cleanly, then raise the quota.',
  },
  {
    key: 'drive-corpus-inventory-bite',
    title: 'Drive Corpus Inventory Bite',
    jobType: 'corpus_inventory',
    lane: 'archive',
    priority: 'P1',
    cadence: 'daily mission: one folder inventory bite now, five filed extractions later',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=drive-corpus-backfill'],
    sourceIds: ['SRC-GDRIVE-001'],
    description: 'Inventories one Google Drive corpus folder/page into the crawl ledger without moving, copying, exporting, or using an LLM.',
    nextAction: 'Run one Drive inventory bite per day until the folder queue is mapped; then add the separate filed-output extraction worker.',
  },
  {
    key: 'drive-content-extract-bite',
    title: 'Drive Content Extraction Bite',
    jobType: 'corpus_extraction',
    lane: 'extract',
    priority: 'P0',
    cadence: 'daily mission: five Drive text outputs',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=drive-content-extract-backfill'],
    sourceIds: ['SRC-GDRIVE-001'],
    description: 'Extracts Google Docs, Google Sheets, PDFs, and plain text files from the Drive inventory queue into source-backed artifacts with file provenance.',
    nextAction: 'Run as a small daily quota mission. Add Slides, Office, images, and video through explicit follow-on extractors with skip reasons.',
  },
  {
    key: 'video-link-inventory-bite',
    title: 'Video Link Inventory Bite',
    jobType: 'corpus_inventory',
    lane: 'archive',
    priority: 'P1',
    cadence: 'manual daily mission: URL-manifest quota now, video extraction quota later',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=video-link-inventory'],
    sourceIds: ['SRC-VIDEO-001', 'SRC-LOOM-001', 'SRC-GDRIVE-001', 'SRC-SKOOL-001', 'SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Inventories Loom, Drive, YouTube, Vimeo, Wistia, Zoom, and Skool media links from existing archives/crawl ledgers without logging into platforms or extracting content.',
    nextAction: 'Keep as a quota mission, not a timer; validate Apify/Loom/Skool extractors on a small authorized batch before any five-video-style daily extraction mission.',
  },
  {
    key: 'video-content-extract-bite',
    title: 'Video Content Extraction Bite',
    jobType: 'corpus_extraction',
    lane: 'extract',
    priority: 'P0',
    cadence: 'daily mission: five video transcript outputs',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'connector_plus_model_later',
    command: 'npm',
    args: ['run', 'extraction:target', '--', '--target=video-content-extract-backfill'],
    sourceIds: ['SRC-VIDEO-001', 'SRC-YOUTUBE-INTEL-001', 'SRC-LOOM-001', 'SRC-GDRIVE-001', 'SRC-SKOOL-001', 'SRC-MEETINGS-001'],
    description: 'Extracts video transcript outputs from the shared video-link manifest. V1 handles YouTube subtitles through DataForSEO; richer video understanding stays behind the multimodal extractor contract.',
    nextAction: 'Run a small daily quota. Add Drive video, Loom, Skool, Zoom, and Gemini/GPT visual review extractors one at a time behind the same queue.',
  },
  {
    key: 'gmail-extract-latest',
    title: 'Gmail Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'daily history mission after Gmail sync',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'gmail:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=3'],
    sourceIds: ['SRC-GMAIL-001'],
    description: 'Extracts governed candidates from archived Gmail threads without a successful processing run for the current content hash.',
    nextAction: 'Run as a daily quota mission until unmined Gmail backlog catches up; raise limits after route latency and spacing are stable.',
  },
  {
    key: 'missive-extract-latest',
    title: 'Missive Candidate Extraction',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'daily history mission after Missive sync',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'missive:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=3'],
    sourceIds: ['SRC-MISSIVE-001'],
    description: 'Extracts governed candidates from archived Missive conversations without a successful processing run for the current content hash, including internal comments.',
    nextAction: 'Run as a daily quota mission until unmined Missive backlog catches up; raise limits after route latency and spacing are stable.',
  },
  {
    key: 'meeting-transcript-gaps',
    title: 'Meeting Transcript Gap Report',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P1',
    cadence: 'weekly',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 300,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'meeting-notes:report-gaps'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Finds recurring meetings and organizers with missing transcripts so Meet defaults can be fixed.',
    nextAction: 'Run after the next few meetings to confirm the Gemini default change worked.',
  },
  {
    key: 'meeting-transcript-recent-gap-verify',
    title: 'Meeting Recent Gap Verifier',
    jobType: 'health_check',
    lane: 'coverage',
    priority: 'P1',
    cadence: 'after recent gap report shows missing transcript artifacts',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'meeting-notes:verify-recent-gaps', '--', '--days=14'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Classifies recent missing transcript artifacts as true missing, parser/tab miss, owner/account path issue, or meeting-key mismatch before meeting sync is scheduled.',
    nextAction: 'Run manually; use the repair command only for parser/account misses after the report is reviewed.',
  },
  {
    key: 'meeting-transcripts-extract-backlog',
    title: 'Meeting Transcript Extraction Backlog',
    jobType: 'extraction',
    lane: 'extract',
    priority: 'P1',
    cadence: 'daily history mission until transcript backlog clears',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'meeting-notes:extract-candidates', '--', '--onlyWithoutCandidates=true', '--limit=3'],
    sourceIds: ['SRC-MEETINGS-001'],
    description: 'Mines archived meeting transcripts without a successful processing run for the current content hash using the subscription route with long per-call windows.',
    nextAction: 'Run as a daily quota mission until unmined meeting transcripts catch up; then keep it as the daily extraction lane for new transcripts.',
  },
  {
    key: 'admin-deal-review-readonly',
    title: 'Admin Deal Review Inspection',
    jobType: 'review',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'every 8 hours: marked Admin re-reviews only',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 480,
    maxRuntimeSeconds: 600,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'deal-review:admin', '--', '--queued', '--limit=10', '--write'],
    sourceIds: ['SRC-OWNERS-001', 'SRC-FUB-001'],
    servesHubs: ['ops'],
    systemSummary: 'Inspects marked Admin deal re-reviews where Ops changed THIS ROW ONLY: REVIEW ACTION to Review This Deal. Scheduled writeback only populates AI review status, action, and findings; it does not auto-fix source fields.',
    systemInputs: ['SRC-OWNERS-001 Admin deal rows', 'SRC-FUB-001 person records', 'Queued review action cells'],
    systemOutputs: ['Ops inbox issue cards', 'AI review status/action/findings in the Admin tab', 'Foundation job run status'],
    description: 'Runs explicit Admin re-reviews after Ops fixes source rows.',
    nextAction: 'Keep source-field corrections human-owned until Ops approves an apply/fix lane.',
  },
  {
    key: 'admin-deal-backlog-review',
    title: 'Admin Deal Backlog Inspection',
    jobType: 'review',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'daily: five newest eligible Admin backlog deals',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 1200,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'deal-review:admin', '--', '--backlog', '--backlog-limit=5', '--backlog-since=2025-06-01', '--write'],
    sourceIds: ['SRC-OWNERS-001', 'SRC-FUB-001', 'SRC-CLICKUP-001'],
    servesHubs: ['ops'],
    systemSummary: 'Inspects five newest eligible Admin backlog deals per day from the June 2025 merger cutoff using Date Firm (Executed) and a 10-day maturity gate. Post-2026-04-01 follow-through is checked against ClickUp Deal Data Entry, not the old Freedom review sheet. Scheduled writeback only populates AI review status, action, and findings; it does not auto-fix source fields.',
    systemInputs: ['SRC-OWNERS-001 Admin deal rows', 'SRC-FUB-001 person records', 'SRC-CLICKUP-001 Deal Data Entry tasks', 'Blank / not-reviewed rows and stale pre-ClickUp reviews from June 2025 onward'],
    systemOutputs: ['Ops inbox issue cards', 'AI review status/action/findings in the Admin tab', 'Foundation job run status'],
    description: 'Runs the paced first-pass Admin backlog inspection lane for mature firm deals.',
    nextAction: 'Keep source-field corrections human-owned until Ops approves an apply/fix lane.',
  },
  {
    key: 'conditional-deal-review-readonly',
    title: 'Conditional Deal Forecast Sync',
    jobType: 'sync',
    lane: 'transactions',
    priority: 'P1',
    cadence: 'every 8 hours: rebuild ClickUp conditional forecast',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 480,
    maxRuntimeSeconds: 600,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'clickup:conditional-forecast'],
    sourceIds: ['SRC-CLICKUP-001', 'SRC-OWNERS-001'],
    servesHubs: ['ops'],
    systemSummary: 'Rebuilds the Owners Dashboard Listings and Conditional Deals tab from ClickUp Deal Data Entry conditional tasks. Buyer/seller conditional tags determine the lane; mutual-release tags are excluded as dead deals. The generated sheet preserves a Review This Conditional action for fixed rows that need a re-check and buckets conditional Net To Team into rolling closing-date collection-month forecast windows.',
    systemInputs: ['SRC-CLICKUP-001 Deal Data Entry conditional tasks', 'ClickUp buyer/seller conditional tags', 'ClickUp mutual-release tags'],
    systemOutputs: ['ClickUp-generated Listings and Conditional Deals forecast', 'Conditional pipeline missing-data summary', 'Foundation job run status'],
    description: 'Keeps the conditional forecast sheet source-backed from ClickUp instead of the disconnected legacy conditional sheet.',
    nextAction: 'Use the preserved Review This Conditional action for missing-data re-checks; keep closing dates maintained so the collection-month buckets remain true cash-date forecasting instead of conditional-deadline forecasting.',
  },
  {
    key: 'agent-roster-review',
    title: 'Agent Onboarding / Roster Inspection',
    jobType: 'review',
    lane: 'people',
    priority: 'P1',
    cadence: 'every 8 hours: inspect ClickUp Agent onboarding and roster accountability',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 480,
    maxRuntimeSeconds: 300,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'agent-roster:review'],
    sourceIds: ['SRC-CLICKUP-001'],
    servesHubs: ['ops'],
    systemSummary: 'Reads the ClickUp Agent Roster as the v1 people-accountability source, surfaces roster blockers, and writes 30/60/90 onboarding-feedback results back to the roster status/score/feedback fields.',
    systemInputs: ['SRC-CLICKUP-001 Agent Roster list', 'Contract Link and contract package fields', 'Roster baseline fields', 'Onboarding NPS 30/60/90 fields'],
    systemOutputs: ['Ops inbox roster accountability cards', 'Foundation job run status'],
    description: 'Keeps the agent roster accountable and mirrors private onboarding-feedback responses back into ClickUp result fields.',
    nextAction: 'Steve, Carson, and Clare will hide/delete field clutter manually; AIOS should only validate the roster source and surface real missing accountability items.',
  },
  {
    key: 'agent-feedback-auto-send-readiness',
    title: 'Agent Feedback Auto-Send Readiness',
    jobType: 'send_readiness',
    lane: 'people',
    priority: 'P1',
    cadence: 'daily dry-run/report only',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 300,
    budget: 'connector',
    command: 'npm',
    args: ['run', 'agent-feedback:auto-send', '--', '--mode=dry-run'],
    sourceIds: ['SRC-CLICKUP-001'],
    servesHubs: ['ops'],
    systemSummary: 'Scans the ClickUp Agent Roster for 30/60/90 onboarding feedback candidates and reports what would send without sending Gmail or writing ClickUp Requested by default.',
    systemInputs: ['SRC-CLICKUP-001 Agent Roster tasks', 'Real Start Date', 'Company Email for internal/team recipients', 'Personal Email for external agents', 'Onboarding NPS 30/60/90 fields'],
    systemOutputs: ['Metadata-only would-send/skipped/blocked/warning/repair counts', 'Runtime Health/Ops readiness proof', 'No raw emails, token URLs, or feedback content'],
    description: 'Runs the governed Agent Onboarding Feedback auto-send readiness scanner. Live sends require both AGENT_FEEDBACK_AUTO_SEND_ENABLED=true and an approved mode/allowlist artifact.',
    nextAction: 'Keep dry-run/report-only until Steve separately approves test-only Georgia/day-30 or later production-all mode through a separate approval artifact.',
  },
  {
    key: 'shared-comms-intelligence-bite',
    title: 'Strategy Intelligence Synthesis Bite',
    jobType: 'intelligence_bite',
    lane: 'synthesis',
    priority: 'P0',
    cadence: 'manual during strategy prep or action review',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'shared-comms:intelligence-bite'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Synthesizes already-mined shared-comms candidates into Strategy Hub/action-router input. Extraction miners run separately so slow subscription calls do not block leadership work.',
    nextAction: 'Run monitored synthesis-only proofs, then route synthesized items into decisions, contradictions, and owner-bound actions.',
  },
  {
    key: 'shared-comms-synthesis-v1',
    title: 'Shared Comms Strategy Synthesis V1',
    jobType: 'synthesis',
    lane: 'synthesis',
    priority: 'P0',
    cadence: 'after fresh extraction batches',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'synthesis:brief', '--', '--limit=120', '--maxItems=12'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Turns candidates and source-backed facts into ranked Strategy Hub/action-router input instead of a raw mining dump.',
    nextAction: 'Run monitored subscription-route proofs with the long synthesis timeout, then connect outputs to the action router.',
  },
  {
    key: 'intelligence-synthesis-spine-refresh',
    title: 'Intelligence Spine Synthesis Refresh',
    jobType: 'synthesis',
    lane: 'synthesis',
    priority: 'P0',
    cadence: 'daily governed spine refresh',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'intelligence:synthesis-refresh'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Keeps the source -> atom -> chunk -> embedding -> fact -> synthesis spine alive on a scheduled worker path instead of depending on manual builder proof runs.',
    nextAction: 'Use as the v1 scheduled refresh lane; proofs remain manual and backlog-mutating acceptance checks stay out of the worker schedule.',
  },
  {
    key: 'intelligence-action-router-proposals',
    title: 'Intelligence Action Router Proposals',
    jobType: 'routing',
    lane: 'action',
    priority: 'P0',
    cadence: 'daily after synthesis refresh',
    enabled: true,
    runtimeMode: 'scheduled',
    scheduleEveryMinutes: 1440,
    maxRuntimeSeconds: 600,
    budget: 'no_llm',
    command: 'npm',
    args: ['run', 'intelligence:action-router-proposals'],
    sourceIds: ['SRC-GMAIL-001', 'SRC-MISSIVE-001', 'SRC-MEETINGS-001', 'SRC-SLACK-001'],
    description: 'Creates pending, human-approval-required routes from governed synthesized items into decisions, backlog, open questions, ignore/snooze, and owner-bound action lanes.',
    nextAction: 'Review pending routes before applying destination writes. No route lands in an operating ledger without explicit human approval.',
  },
  {
    key: 'strategy-evidence-packet-v1',
    title: 'Strategy Evidence Packet V1',
    jobType: 'synthesis',
    lane: 'strategy',
    priority: 'P0',
    cadence: 'manual during quarterly strategy prep',
    enabled: true,
    runtimeMode: 'manual',
    scheduleEveryMinutes: null,
    maxRuntimeSeconds: 3900,
    budget: 'llm_limited',
    command: 'npm',
    args: ['run', 'strategy:evidence-packet', '--', '--limit=180', '--artifactLimit=28', '--maxItems=18'],
    sourceIds: [
      'SRC-STRATEGY-001',
      'SRC-GDRIVE-001',
      'SRC-MEETINGS-001',
      'SRC-GMAIL-001',
      'SRC-MISSIVE-001',
      'SRC-SLACK-001',
      'SRC-YOUTUBE-INTEL-001',
      'SRC-FUB-001',
      'SRC-SUPABASE-001',
      'SRC-FINANCE-001',
      'SRC-OWNERS-001',
      'SRC-CLICKUP-001',
    ],
    servesHubs: ['strategy'],
    description: 'Builds the owner-level strategy packet from mined candidates, direct Drive/video strategy artifacts, source-backed operating facts, current strategy docs, backlog, decisions, and extraction/runtime coverage.',
    nextAction: 'Use the generated packet for Steve strategy review, then route accepted issues into Strategic Execution, Decisions, Backlog, and Action Router.',
  },
]

export function getFoundationJobDefinitions() {
  return foundationJobDefinitions.map(job => ({
    ...job,
    args: job.args.slice(),
    sourceIds: job.sourceIds.slice(),
  }))
}

export function getFoundationJobDefinition(jobKey) {
  const normalized = String(jobKey || '').trim()
  return getFoundationJobDefinitions().find(job => job.key === normalized) || null
}

export function getFoundationJobRuntime(job, latestRun, now = new Date()) {
  const runtimeMode = job.runtimeMode || (job.enabled ? 'manual' : 'paused')
  const scheduleEveryMinutes = Number(job.scheduleEveryMinutes) > 0 ? Number(job.scheduleEveryMinutes) : null
  const latestTime = latestRun?.finishedAt || latestRun?.startedAt || latestRun?.createdAt || null
  const latestAt = latestTime ? new Date(latestTime) : null
  const latestValid = latestAt && !Number.isNaN(latestAt.getTime())
  const running = latestRun?.status === 'running' || latestRun?.status === 'queued'

  if (!job.enabled || runtimeMode === 'paused') {
    return {
      runtimeMode: 'paused',
      due: false,
      nextRunAt: null,
      scheduleStatus: 'paused',
      scheduleDetail: job.pauseReason ? `Paused: ${job.pauseReason}` : 'Paused or disabled.',
    }
  }

  if (runtimeMode !== 'scheduled') {
    return {
      runtimeMode: 'manual',
      due: false,
      nextRunAt: null,
      scheduleStatus: 'manual',
      scheduleDetail: 'Manual-only until explicitly scheduled.',
    }
  }

  if (!scheduleEveryMinutes) {
    return {
      runtimeMode: 'manual',
      due: false,
      nextRunAt: null,
      scheduleStatus: 'manual',
      scheduleDetail: 'No schedule interval configured.',
    }
  }

  if (!latestValid) {
    return {
      runtimeMode: 'scheduled',
      due: !running,
      nextRunAt: now.toISOString(),
      scheduleStatus: running ? 'running' : 'due',
      scheduleDetail: running ? 'Running now.' : 'Due now: no prior run recorded.',
    }
  }

  const nextRun = new Date(latestAt.getTime() + scheduleEveryMinutes * 60 * 1000)
  const due = !running && nextRun.getTime() <= now.getTime()
  const minutesUntilDue = Math.ceil((nextRun.getTime() - now.getTime()) / 60000)

  return {
    runtimeMode: 'scheduled',
    due,
    nextRunAt: nextRun.toISOString(),
    scheduleStatus: running ? 'running' : due ? 'due' : 'scheduled',
    scheduleDetail: running
      ? 'Running now.'
      : due
        ? `Due now. Scheduled every ${scheduleEveryMinutes} minutes.`
        : `Next run in ${Math.max(0, minutesUntilDue)} minutes.`,
  }
}
